var localEmotions = new Map();
localEmotions.set("[最右]", require('../../img/emotions/d_zuiyou.png'));
localEmotions.set("[爱你]", require('../../img/emotions/d_aini.png'));
localEmotions.set("[拜拜]", require('../../img/emotions/d_baibai.png'));
localEmotions.set("[悲伤]", require('../../img/emotions/d_beishang.png'));
localEmotions.set("[鄙视]", require('../../img/emotions/d_bishi.png'));
localEmotions.set("[闭嘴]", require('../../img/emotions/d_bizui.png'));
localEmotions.set("[挤眼]", require('../../img/emotions/d_jiyan.png'));
localEmotions.set("[馋嘴]", require('../../img/emotions/d_chanzui.png'));
localEmotions.set("[吃惊]", require('../../img/emotions/d_chijing.png'));
localEmotions.set("[允悲]", require('../../img/emotions/d_yunbei.png'));
localEmotions.set("[憧憬]", require('../../img/emotions/d_chongjing.png'));
localEmotions.set("[费解]", require('../../img/emotions/d_feijie.png'));
localEmotions.set("[并不简单]", require('../../img/emotions/d_bingbujiandan.png'));
localEmotions.set("[笑而不语]", require('../../img/emotions/d_xiaoerbuyu.png'));
localEmotions.set("[哆啦A梦吃惊]", require('../../img/emotions/dl_chijing.png'));
localEmotions.set("[哆啦A梦微笑]", require('../../img/emotions/dl_weixiao.png'));
localEmotions.set("[哆啦A梦花心]", require('../../img/emotions/dl_huaxin.png'));
localEmotions.set("[doge]", require('../../img/emotions/d_doge.png'));
localEmotions.set("[喵喵]", require('../../img/emotions/d_miao.png'));
localEmotions.set("[二哈]", require('../../img/emotions/d_erha.png'));
localEmotions.set("[抱抱]", require('../../img/emotions/d_baobao.png'));
localEmotions.set("[摊手]", require('../../img/emotions/d_tanshou.png'));
localEmotions.set("[骷髅]", require('../../img/emotions/d_kulou.png'));
localEmotions.set("[污]", require('../../img/emotions/d_wu.png'));
localEmotions.set("[舔屏]", require('../../img/emotions/d_tian.png'));
localEmotions.set("[打哈欠]", require('../../img/emotions/d_dahaqi.png'));
localEmotions.set("[顶]", require('../../img/emotions/d_ding.png'));
localEmotions.set("[坏笑]", require('../../img/emotions/d_huaixiao.png'));
localEmotions.set("[神兽]", require('../../img/emotions/d_shenshou.png'));
localEmotions.set("[奥特曼]", require('../../img/emotions/d_aoteman.png'));
localEmotions.set("[打脸]", require('../../img/emotions/d_dalian.png'));
localEmotions.set("[愤怒]", require('../../img/emotions/d_fennu.png'));
localEmotions.set("[感冒]", require('../../img/emotions/d_ganmao.png'));
localEmotions.set("[鼓掌]", require('../../img/emotions/d_guzhang.png'));
localEmotions.set("[哈哈]", require('../../img/emotions/d_haha.png'));
localEmotions.set("[害羞]", require('../../img/emotions/d_haixiu.png'));
localEmotions.set("[汗]", require('../../img/emotions/d_han.png'));
localEmotions.set("[呵呵]", require('../../img/emotions/d_hehe.png'));
localEmotions.set("[黑线]", require('../../img/emotions/d_heixian.png'));
localEmotions.set("[哼]", require('../../img/emotions/d_heng.png'));
localEmotions.set("[色]", require('../../img/emotions/d_huaxin.png'));
localEmotions.set("[可爱]", require('../../img/emotions/d_keai.png'));
localEmotions.set("[可怜]", require('../../img/emotions/d_kelian.png'));
localEmotions.set("[酷]", require('../../img/emotions/d_ku.png'));
localEmotions.set("[困]", require('../../img/emotions/d_kun.png'));
localEmotions.set("[懒得理你]", require('../../img/emotions/d_landelini.png'));
localEmotions.set("[泪]", require('../../img/emotions/d_lei.png'));
localEmotions.set("[怒]", require('../../img/emotions/d_nu.png'));
localEmotions.set("[怒骂]", require('../../img/emotions/d_numa.png'));
localEmotions.set("[女孩儿]", require('../../img/emotions/d_nvhaier.png'));
localEmotions.set("[钱]", require('../../img/emotions/d_qian.png'));
localEmotions.set("[亲亲]", require('../../img/emotions/d_qinqin.png'));
localEmotions.set("[生病]", require('../../img/emotions/d_shengbing.png'));
localEmotions.set("[失望]", require('../../img/emotions/d_shiwang.png'));
localEmotions.set("[衰]", require('../../img/emotions/d_shuai.png'));
localEmotions.set("[书呆子]", require('../../img/emotions/d_shudaizi.png'));
localEmotions.set("[睡觉]", require('../../img/emotions/d_shuijiao.png'));
localEmotions.set("[思考]", require('../../img/emotions/d_sikao.png'));
localEmotions.set("[太开心]", require('../../img/emotions/d_taikaixin.png'));
localEmotions.set("[偷笑]", require('../../img/emotions/d_touxiao.png'));
localEmotions.set("[吐]", require('../../img/emotions/d_tu.png'));
localEmotions.set("[兔子]", require('../../img/emotions/d_tuzi.png'));
localEmotions.set("[挖鼻]", require('../../img/emotions/d_wabishi.png'));
localEmotions.set("[委屈]", require('../../img/emotions/d_weiqu.png'));
localEmotions.set("[笑cry]", require('../../img/emotions/d_xiaoku.png'));
localEmotions.set("[熊猫]", require('../../img/emotions/d_xiongmao.png'));
localEmotions.set("[嘻嘻]", require('../../img/emotions/d_xixi.png'));
localEmotions.set("[嘘]", require('../../img/emotions/d_xu.png'));
localEmotions.set("[阴险]", require('../../img/emotions/d_yinxian.png'));
localEmotions.set("[疑问]", require('../../img/emotions/d_yiwen.png'));
localEmotions.set("[右哼哼]", require('../../img/emotions/d_youhengheng.png'));
localEmotions.set("[晕]", require('../../img/emotions/d_yun.png'));
localEmotions.set("[抓狂]", require('../../img/emotions/d_zhuakuang.png'));
localEmotions.set("[猪头]", require('../../img/emotions/d_zhutou.png'));
localEmotions.set("[做鬼脸]", require('../../img/emotions/d_zuoguilian.png'));
localEmotions.set("[左哼哼]", require('../../img/emotions/d_zuohengheng.png'));
localEmotions.set("[肥皂]", require('../../img/emotions/d_feizao.png'));
localEmotions.set("[给力]", require('../../img/emotions/f_geili.png'));
localEmotions.set("[互粉]", require('../../img/emotions/f_hufen.png'));
localEmotions.set("[囧]", require('../../img/emotions/f_jiong.png'));
localEmotions.set("[萌]", require('../../img/emotions/f_meng.png'));
localEmotions.set("[神马]", require('../../img/emotions/f_shenma.png'));
localEmotions.set("[帅]", require('../../img/emotions/f_shuai.png'));
localEmotions.set("[威武]", require('../../img/emotions/f_v5.png'));
localEmotions.set("[喜]", require('../../img/emotions/f_xi.png'));
localEmotions.set("[织]", require('../../img/emotions/f_zhi.png'));
localEmotions.set("[haha]", require('../../img/emotions/h_haha.png'));
localEmotions.set("[不要]", require('../../img/emotions/h_buyao.png'));
localEmotions.set("[good]", require('../../img/emotions/h_good.png'));
localEmotions.set("[来]", require('../../img/emotions/h_lai.png'));
localEmotions.set("[ok]", require('../../img/emotions/h_ok.png'));
localEmotions.set("[拳头]", require('../../img/emotions/h_quantou.png'));
localEmotions.set("[弱]", require('../../img/emotions/h_ruo.png'));
localEmotions.set("[握手]", require('../../img/emotions/h_woshou.png'));
localEmotions.set("[耶]", require('../../img/emotions/h_ye.png'));
localEmotions.set("[赞]", require('../../img/emotions/h_zan.png'));
localEmotions.set("[最差]", require('../../img/emotions/h_zuicha.png'));
localEmotions.set("[心]", require('../../img/emotions/l_xin.png'));
localEmotions.set("[伤心]", require('../../img/emotions/l_shangxin.png'));
localEmotions.set("[爱心传递]", require('../../img/emotions/l_aixinchuandi.png'));
localEmotions.set("[冰棍]", require('../../img/emotions/o_bingun.png'));
localEmotions.set("[电影]", require('../../img/emotions/o_dianying.png'));
localEmotions.set("[发红包]", require('../../img/emotions/o_fahongbao.png'));
localEmotions.set("[飞机]", require('../../img/emotions/o_feiji.png'));
localEmotions.set("[风扇]", require('../../img/emotions/o_fengshan.png'));
localEmotions.set("[干杯]", require('../../img/emotions/o_ganbei.png'));
localEmotions.set("[红丝带]", require('../../img/emotions/o_hongsidai.png'));
localEmotions.set("[话筒]", require('../../img/emotions/o_huatong.png'));
localEmotions.set("[咖啡]", require('../../img/emotions/o_kafei.png'));
localEmotions.set("[蜡烛]", require('../../img/emotions/o_lazhu.png'));
localEmotions.set("[礼物]", require('../../img/emotions/o_liwu.png'));
localEmotions.set("[绿丝带]", require('../../img/emotions/o_lvsidai.png'));
localEmotions.set("[汽车]", require('../../img/emotions/o_qiche.png'));
localEmotions.set("[实习]", require('../../img/emotions/o_shixi.png'));
localEmotions.set("[手机]", require('../../img/emotions/o_shouji.png'));
localEmotions.set("[手套]", require('../../img/emotions/o_shoutao.png'));
localEmotions.set("[围脖]", require('../../img/emotions/o_weibo.png'));
localEmotions.set("[围观]", require('../../img/emotions/o_weiguan.png'));
localEmotions.set("[温暖帽子]", require('../../img/emotions/o_wennuanmaozi.png'));
localEmotions.set("[西瓜]", require('../../img/emotions/o_xigua.png'));
localEmotions.set("[音乐]", require('../../img/emotions/o_yinyue.png'));
localEmotions.set("[照相机]", require('../../img/emotions/o_zhaoxiangji.png'));
localEmotions.set("[钟]", require('../../img/emotions/o_zhong.png'));
localEmotions.set("[自行车]", require('../../img/emotions/o_zixingche.png'));
localEmotions.set("[足球]", require('../../img/emotions/o_zuqiu.png'));
localEmotions.set("[浮云]", require('../../img/emotions/w_fuyun.png'));
localEmotions.set("[落叶]", require('../../img/emotions/w_luoye.png'));
localEmotions.set("[沙尘暴]", require('../../img/emotions/w_shachenbao.png'));
localEmotions.set("[太阳]", require('../../img/emotions/w_taiyang.png'));
localEmotions.set("[微风]", require('../../img/emotions/w_weifeng.png'));
localEmotions.set("[鲜花]", require('../../img/emotions/w_xianhua.png'));
localEmotions.set("[下雨]", require('../../img/emotions/w_xiayu.png'));
localEmotions.set("[雪]", require('../../img/emotions/w_xue.png'));
localEmotions.set("[雪人]", require('../../img/emotions/w_xueren.png'));
localEmotions.set("[月亮]", require('../../img/emotions/w_yueliang.png'));
localEmotions.set("[悲催]", require('../../img/emotions/lxh_beicui.png'));
localEmotions.set("[被电]", require('../../img/emotions/lxh_beidian.png'));
localEmotions.set("[崩溃]", require('../../img/emotions/lxh_bengkui.png'));
localEmotions.set("[别烦我]", require('../../img/emotions/lxh_biefanwo.png'));
localEmotions.set("[不好意思]", require('../../img/emotions/lxh_buhaoyisi.png'));
localEmotions.set("[不想上班]", require('../../img/emotions/lxh_buxiangshangban.png'));
localEmotions.set("[得意地笑]", require('../../img/emotions/lxh_deyidexiao.png'));
localEmotions.set("[给劲]", require('../../img/emotions/lxh_feijin.png'));
localEmotions.set("[好爱哦]", require('../../img/emotions/lxh_haoaio.png'));
localEmotions.set("[好棒]", require('../../img/emotions/lxh_haobang.png'));
localEmotions.set("[好囧]", require('../../img/emotions/lxh_haojiong.png'));
localEmotions.set("[好喜欢]", require('../../img/emotions/lxh_haoxihuan.png'));
localEmotions.set("[hold住]", require('../../img/emotions/lxh_holdzhu.png'));
localEmotions.set("[杰克逊]", require('../../img/emotions/lxh_jiekexun.png'));
localEmotions.set("[纠结]", require('../../img/emotions/lxh_jiujie.png'));
localEmotions.set("[巨汗]", require('../../img/emotions/lxh_juhan.png'));
localEmotions.set("[抠鼻屎]", require('../../img/emotions/lxh_koubishi.png'));
localEmotions.set("[困死了]", require('../../img/emotions/lxh_kunsile.png'));
localEmotions.set("[雷锋]", require('../../img/emotions/lxh_leifeng.png'));
localEmotions.set("[泪流满面]", require('../../img/emotions/lxh_leiliumanmian.png'));
localEmotions.set("[玫瑰]", require('../../img/emotions/lxh_meigui.png'));
localEmotions.set("[噢耶]", require('../../img/emotions/lxh_oye.png'));
localEmotions.set("[霹雳]", require('../../img/emotions/lxh_pili.png'));
localEmotions.set("[瞧瞧]", require('../../img/emotions/lxh_qiaoqiao.png'));
localEmotions.set("[丘比特]", require('../../img/emotions/lxh_qiubite.png'));
localEmotions.set("[求关注]", require('../../img/emotions/lxh_qiuguanzhu.png'));
localEmotions.set("[群体围观]", require('../../img/emotions/lxh_quntiweiguan.png'));
localEmotions.set("[甩甩手]", require('../../img/emotions/lxh_shuaishuaishou.png'));
localEmotions.set("[偷乐]", require('../../img/emotions/lxh_toule.png'));
localEmotions.set("[推荐]", require('../../img/emotions/lxh_tuijian.png'));
localEmotions.set("[互相膜拜]", require('../../img/emotions/lxh_xianghumobai.png'));
localEmotions.set("[想一想]", require('../../img/emotions/lxh_xiangyixiang.png'));
localEmotions.set("[笑哈哈]", require('../../img/emotions/lxh_xiaohaha.png'));
localEmotions.set("[羞嗒嗒]", require('../../img/emotions/lxh_xiudada.png'));
localEmotions.set("[许愿]", require('../../img/emotions/lxh_xuyuan.png'));
localEmotions.set("[有压力]", require('../../img/emotions/lxh_youyali.png'));
localEmotions.set("[赞啊]", require('../../img/emotions/lxh_zana.png'));
localEmotions.set("[震惊]", require('../../img/emotions/lxh_zhenjing.png'));
localEmotions.set("[转发]", require('../../img/emotions/lxh_zhuanfa.png'));
//
localEmotions.set("[微笑]", require('../../img/emotions/bx.png'));

// Loat Local emotions
var emotions = require('./emotions.json');
var values = emotions.map((item)=>{return item.value.substring(1, item.value.length-1)});
var  regexp = values.join('|');

function getSource(name) {
  // 当emotions没有更新时, 必须是null
  var t = localEmotions.get(name);
  return t;
}

const Emotion = {
  emotions,
  getSource,
  regexp,
}

export default Emotion;
